version: "3"

services:
  freeradius:
    build:
      context: .
      dockerfile: Dockerfile.freeradius
    image: freeradius
    container_name: freeradius
    ports:
      - "1812-1813:1812-1813/udp"
    command: -X # Enable debugging output
    restart: unless-stopped
#     networks:
#       - nginx-radius

# networks:
#   nginx-radius:
#     external: true
